공공데이터활용/dataMiniProject/routes/nationWide_route.py
import math
from tkinter import messagebox as msg
from tkinter import Tk

import pyautogui as pg

from itertools import zip_longest

from flask import Flask, request, render_template, redirect, Blueprint
import models as mo
import matplotlib.pyplot as plt

bp = Blueprint('nationWide', __name__, url_prefix='/nationWide')

service = mo.NationWideService()
boardService = mo.BoardService()

@bp.route('/nationWide_info', methods=['POST', 'GET'])
def nationWide_info():

    page = request.args.get('page', type=int, default=1)  # 페이지
    nationWide = service.getAll()  # DB에 저장되게 다시 코딩해야되나?? 리퀘스트가 너무많고 리스폰도 너무 느려진다. 한번 불러온다음 객체에 저장되어있게끔 못하는건가?
    nationWide = nationWide.paginate(page, per_page=5)

    return render_template(
        'nationWide/nationWideInfo.html',
        page=page, nationWide=nationWide)

@bp.route('/api_to_db', methods=['POST', 'GET'])
def api_to_db():

    service.getRouteInfo()

    # 얼랏방식 메시지박스
    # a = pg.alert(text='데이터가 최신화 되었습니다.', title='알림창', button='OK')
    # print(a)

    # tkinter 방식 메시지 박스
    msg.showinfo('알림창', '데이터가 최신화 되었습니다.')
    return render_template('index.html')


@bp.route('/detail/<int:num>') #<a href="/board/detail/{{b.num}}">
def detail(num):
   b = service.getNationWide(num)
   print(num)
   d= b.itsBroNm
   print(d)
   c = boardService.getAll(d)
   return render_template('nationWide/nationWideInfoDetail.html', b=b, c=c, num=num)



@bp.route('/route-path', methods=['POST'])
def route_path():
    routeid = request.form['routeid']
    stList:list = service.getStListByRouteId(routeId=routeid)
    return render_template('nationWide/stList.html', stList=stList, routeid=routeid)

@bp.route('/graph')#get 방식
def graph():
    img_path = '../static/graph/my_plot.png'

    x = [1, 2, 3, 4]
    y = [3, 8, 5, 6]
    fig, ax = plt.subplots()#그래프 이미지 객체 생성
    plt.plot(x, y) #fig 객체에 그래프를 그림
    fig.savefig(img_path)#fig 객체를 파라메터로 지정한 패스의 파일로 저장
    img_path = '/' + img_path
    return render_template('graph.html', img_path=img_path)

공공데이터활용/dataMiniProject/templates/nationWide/nationWideInfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>nationWide</title>

<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="../static/images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../static/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../static/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../static/vendor/animate/animate.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../static/vendor/select2/select2.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../static/vendor/perfect-scrollbar/perfect-scrollbar.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../static/css/util.css">
	<link rel="stylesheet" type="text/css" href="../static/css/main.css">
<!--===============================================================================================-->

</head>
<body>

<div><a href="/">홈</a></div>
<div style="display:block; font-size:80px; margin-left:auto; margin-right:auto; text-align:center; text-color:#36304a;">전국맛집랭킹</div>

<div  style="display:block; margin-left:auto; margin-right:auto; text-align:center; margin-top:20px;"> <!--지도랑 사진 묶어놓은 block-->

<table class="mainTable" style="margin-left:auto; margin-right:auto;">
    <tr>
        <td>
        <div id="map" style="border:3px solid #36304a; width:600px;height:575px;"></div>

        <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=8cc54ee7ce95116e097e9eae4d3b963f&libraries=services"></script>
        <script>
        var mapContainer = document.getElementById('map'), // 지도를 표시할 div
            mapOption = {
                center : new kakao.maps.LatLng(36.2683, 127.6358), // 지도의 중심좌표
                level : 14 // 지도의 확대 레벨
            };

        // 지도를 생성합니다
        var map = new kakao.maps.Map(mapContainer, mapOption);

        // 주소-좌표 변환 객체를 생성합니다
        var geocoder = new kakao.maps.services.Geocoder();


        // 주소 변수에 저장

        var addressList = []

        // 주소로 좌표를 검색합니다
        {% for s in nationWide.items %}
        for (var i = 0; i < 1; i ++) {
            geocoder.addressSearch('{{s.dtlAddrNm}}', function(result, status) {
                console.log(i);
                // 정상적으로 검색이 완료됐으면
                 if (status === kakao.maps.services.Status.OK) {

                    var coords = new kakao.maps.LatLng(result[0].y, result[0].x);

                    addressList.push(coords);

                    // 마커 이미지
                    var imageSrc = "https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/markerStar.png";

                    // 마커 이미지의 이미지 크기 입니다
                    var imageSize = new kakao.maps.Size(24, 35);

                    // 마커 이미지를 생성합니다
                    var markerImage = new kakao.maps.MarkerImage(imageSrc, imageSize);

                    var marker = new kakao.maps.Marker({
                        map: map, // 마커를 표시할 지도
                        title : '지도', // 마커의 타이틀, 마커에 마우스를 올리면 타이틀이 표시됩니다
                        position: coords, // 마커를 표시할 위치
                        image : markerImage // 마커 이미지
                    });



                    var iwContent = '<div style="padding:5px; ">랭킹:{{s.rk}} / {{s.itsBroNm}}</div>', // 인포윈도우에 표출될 내용으로 HTML 문자열이나 document element가 가능합니다
                    iwRemoveable = true; // removeable 속성을 ture 로 설정하면 인포윈도우를 닫을 수 있는 x버튼이 표시됩니다

                    // 인포윈도우를 생성합니다
                    var infowindow = new kakao.maps.InfoWindow({
                        content : iwContent,
                    });


                    // 마커에 mouseover 이벤트와 mouseout 이벤트를 등록합니다
                    // 이벤트 리스너로는 클로저를 만들어 등록합니다
                    // for문에서 클로저를 만들어 주지 않으면 마지막 마커에만 이벤트가 등록됩니다
                    kakao.maps.event.addListener(marker, 'mouseover', makeOverListener(map, marker, infowindow));
                    kakao.maps.event.addListener(marker, 'mouseout', makeOutListener(infowindow));

                    // 인포윈도우를 표시하는 클로저를 만드는 함수입니다
                    function makeOverListener(map, marker, infowindow) {
                        return function() {
                            infowindow.open(map, marker);
                        };
                    }

                    // 인포윈도우를 닫는 클로저를 만드는 함수입니다
                    function makeOutListener(infowindow) {
                        return function() {
                            infowindow.close();
                        };
                    }

                    kakao.maps.event.addListener(marker, 'click', function() {
                          // 클릭 이벤트 발동시 해당 링크로 이동합니다.
                          location.href='/nationWide/detail/{{s.rk}}';
                    });


                }
            })
        };
        {% endfor %}

        console.log(addressList);


        </script>
    </td>


    <td>
        <div class="limiter">
            <div class="container-table100">
                <div class="wrap-table100">
                    <div class="table100" >
                        <table class="subTable" >
                           <thead>
                                <tr class="table100-head">
                                    <th>랭킹</th>
                                    <th>사진</th>
                                    <th>상호</th>
                                    <th>지역이름</th>
                                    <th>상세주소</th>
                                </tr>
                           </thead>
                            {% for s in nationWide.items %}
                            <tbody>
                                <tr style="border: 3px solid #f5f5f5;" onclick="location.href='/nationWide/detail/{{s.rk}}'" style="cursor:hand">
                                    <td class="column1">{{s.rk}}</td>
                                    <td class="column2"><img style="width:100px; height:100px;" class="img-concert" src="{{s.imgLink}}" /></td>
                                    <td class="column3">{{s.itsBroNm}}</td>
                                    <td class="column5">{{s.areaNm}}</td>
                                    <td class="column7">{{s.dtlAddrNm}}</td>
                                </tr>
                            </tbody>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
        </div>
        </td>
    </tr>
</table>
</div>
<!--===============================================================================================-->
	<script src="../static/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="../static/vendor/bootstrap/js/popper.js"></script>
	<script src="../static/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="../static/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="../static/js/main.js"></script>




<div style="display:block; margin-right:auto; margin-left:auto; margin-top:30px;">
<!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">

        <!-- 이전페이지 -->
        {% if nationWide.has_prev %}
        <li class="page-item">
            <a class="page-link" href="?page={{ nationWide.prev_num }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}

        <!-- 페이지 리스트를 돌면서 해당 페이지로 이동할 수 있는 링크 -->
        {% for page_num in nationWide.iter_pages() %}
            {% if page_num %}
                {% if page_num != nationWide.page %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                </li>
                {% else %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="#">{{ page_num }}</a>
                </li>
                {% endif %}
           {% else %}
                <li class="disabled">
                    <a class="page-link" href="#">...</a>
                </li>
           {% endif %}
        {% endfor %}


        <!-- 다음페이지 -->
        {% if nationWide.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ nationWide.next_num }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
</div>

</body>
</html>

공공데이터활용/dataMiniProject/templates/nationWide/nationWideInfoDetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>nationWideDetail</title>

</head>
<body>

<div><a href="/">홈</a></div>
<div style="display:block; font-size:80px; margin-left:auto; margin-right:auto; text-align:center; text-color:#36304a;">전국맛집랭킹</div>


<table style="margin-top:100px; margin-right:auto; margin-left:auto; text-align:center">
     <tbody>
        <tr>
            <td><img style="border:1px solid #36304a; width:400px; height:375px;" src="{{b.imgLink}}" /></td>
            <td><div id="map" style="border:1px solid #36304a; width:400px; height:375px;"></div></td>
        </tr>
        <tr style="margin-top:10px; padding:10px; height:50px; font-size:15px;">
            <td colspan="2">랭킹 {{b.rk}} 위</td>
        </tr>

        <tr style="margin-top:10px; padding:10px; height:50px; font-size:20px;">
            <td colspan="2">{{b.itsBroNm}}</td>
        </tr>

        <tr style="margin-top:10px; padding:10px; height:50px; font-size:15px;">
            <td colspan="2">{{b.dtlAddrNm}}</td>
        </tr>



    </tbody>

</table>



<h3 style="text-align:center;">댓글 리뷰</h3>
<!--<a href="/board/add/form/{{num}}">글작성</a><br/>-->

<!--method="POST" enctype="multipart/form-data"-->
<!--<form action="/board/add/form/{{num}}/{{b.itsBroNm}}" method="GET">-->
<!--    <input type="hidden" name="{{b.itsBroNm}}" value="{{b.itsBroNm}}">-->
<!--    <input type="submit" value="작성">-->
<!--</form>-->


<table style="margin-right:auto; margin-left:auto;">
    <tr style="border:1px solid black;"><th>내용</th><th>작성자</th><th>작성일</th></tr>
    {% for w in c %}
        <tr>
<!--            <td><a href="/board/detail/{{b.num}}">{{w.num}}</a></td>-->
            <td style="width:500px;">{{w.content}}</td>
            <td>{{w.writer}}</td>
            <td>{{w.w_date}}</td>
        </tr>
    {% endfor %}
</table>


<form action="/board/add/{{num}}" method="POST" enctype="multipart/form-data">
    <table style="border:2px solid black; margin-right:auto; margin-left:auto;" >
        <tr>
            <th>내용</th><td><textarea name="content" placeholder="리뷰 작성칸" rows="1" cols="60"></textarea></td>
            <th>작성자</th>
            <td><input type="text" name="writer"></td>
            <td><input type="hidden" name="itsBroNm" value="{{b.itsBroNm}}"> </td>
            <td><input type="submit" value="작성"></td>
        </tr>

    </table>
</form>




<div><a href="/nationWide/nationWide_info">뒤로가기</a></div>





    <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=8cc54ee7ce95116e097e9eae4d3b963f&libraries=services"></script>
    <script>


        var mapContainer = document.getElementById('map'), // 지도를 표시할 div
            mapOption = {
                center: new kakao.maps.LatLng(33.450701, 126.570667), // 지도의 중심좌표
                level: 3 // 지도의 확대 레벨
            };

        // 지도를 생성합니다
        var map = new kakao.maps.Map(mapContainer, mapOption);

        // 주소-좌표 변환 객체를 생성합니다
        var geocoder = new kakao.maps.services.Geocoder();

        // 주소로 좌표를 검색합니다
        geocoder.addressSearch('{{b.dtlAddrNm}}', function(result, status) {

            // 정상적으로 검색이 완료됐으면
             if (status === kakao.maps.services.Status.OK) {

                var coords = new kakao.maps.LatLng(result[0].y, result[0].x);

                // 결과값으로 받은 위치를 마커로 표시합니다
                var marker = new kakao.maps.Marker({
                    map: map,
                    position: coords
                });

                // 인포윈도우로 장소에 대한 설명을 표시합니다
                var infowindow = new kakao.maps.InfoWindow({
                    content: '<div style="width:150px;text-align:center;padding:6px 0;">랭킹 : {{b.rk}} / {{b.itsBroNm}} </div>'
                });
                infowindow.open(map, marker);

                // 지도의 중심을 결과값으로 받은 위치로 이동시킵니다
                map.setCenter(coords);
            }
        });


    </script>




</body>
</html>

공공데이터활용/dataMiniProject/templates/nationWide/nationWideInfoDetail_backup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>nationWideDetail</title>

</head>
<body>

<div><a href="/">홈</a></div>
<div style="display:block; font-size:80px; margin-left:auto; margin-right:auto; text-align:center; text-color:#36304a;">전국맛집랭킹</div>


                    <table style="margin-top:100px; margin-right:auto; margin-left:auto; text-align:center">
                         <tbody>
                            <tr>
                                <td><img style="border:1px solid #36304a; width:300px; height:275px;" src="{{b.imgLink}}" /></td>
                                <td><div id="map" style="border:1px solid #36304a; width:300px; height:275px;"></div></td>
                            </tr>
                            <tr style="margin-top:10px; padding:10px; height:50px; font-size:15px;">
                                <td colspan="2">랭킹 {{b.rk}} 위</td>
                            </tr>

                            <tr style="margin-top:10px; padding:10px; height:50px; font-size:20px;">
                                <td colspan="2">{{b.itsBroNm}}</td>
                            </tr>

                            <tr style="margin-top:10px; padding:10px; height:50px; font-size:15px;">
                                <td colspan="2">{{b.dtlAddrNm}}</td>
                            </tr>



                        </tbody>

                    </table>





<div><a href="/nationWide/nationWide_info">뒤로가기</a></div>





    <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=8cc54ee7ce95116e097e9eae4d3b963f&libraries=services"></script>
    <script>


        var mapContainer = document.getElementById('map'), // 지도를 표시할 div
            mapOption = {
                center: new kakao.maps.LatLng(33.450701, 126.570667), // 지도의 중심좌표
                level: 3 // 지도의 확대 레벨
            };

        // 지도를 생성합니다
        var map = new kakao.maps.Map(mapContainer, mapOption);

        // 주소-좌표 변환 객체를 생성합니다
        var geocoder = new kakao.maps.services.Geocoder();

        // 주소로 좌표를 검색합니다
        geocoder.addressSearch('{{b.dtlAddrNm}}', function(result, status) {

            // 정상적으로 검색이 완료됐으면
             if (status === kakao.maps.services.Status.OK) {

                var coords = new kakao.maps.LatLng(result[0].y, result[0].x);

                // 결과값으로 받은 위치를 마커로 표시합니다
                var marker = new kakao.maps.Marker({
                    map: map,
                    position: coords
                });

                // 인포윈도우로 장소에 대한 설명을 표시합니다
                var infowindow = new kakao.maps.InfoWindow({
                    content: '<div style="width:150px;text-align:center;padding:6px 0;">랭킹 : {{b.rk}} / {{b.itsBroNm}} </div>'
                });
                infowindow.open(map, marker);

                // 지도의 중심을 결과값으로 받은 위치로 이동시킵니다
                map.setCenter(coords);
            }
        });


    </script>




</body>
</html>

공공데이터활용/dataMiniProject/templates/nationWide/nationWideInfo_backup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


<div style="display:block;">

    <div id="map" style="display:inline; float:left; width:600px;height:800px;"></div>

    <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=8cc54ee7ce95116e097e9eae4d3b963f&libraries=services"></script>
    <script>
    var mapContainer = document.getElementById('map'), // 지도를 표시할 div
        mapOption = {
            center : new kakao.maps.LatLng(36.2683, 127.6358), // 지도의 중심좌표
            level : 12 // 지도의 확대 레벨
        };

    // 지도를 생성합니다
    var map = new kakao.maps.Map(mapContainer, mapOption);

    // 주소-좌표 변환 객체를 생성합니다
    var geocoder = new kakao.maps.services.Geocoder();


    // 주소 변수에 저장
    var address = '{{nationWide[0].dtlAddrNm}}'

    var addressList = []

    // 주소로 좌표를 검색합니다
    {% for s in toList %}
    for (var i = 0; i < 1; i ++) {
        geocoder.addressSearch('{{s.dtlAddrNm}}', function(result, status) {
            console.log(i);
            // 정상적으로 검색이 완료됐으면
             if (status === kakao.maps.services.Status.OK) {

                var coords = new kakao.maps.LatLng(result[0].y, result[0].x);

                addressList.push(coords);

                // 마커 이미지
                var imageSrc = "https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/markerStar.png";

                // 마커 이미지의 이미지 크기 입니다
                var imageSize = new kakao.maps.Size(24, 35);

                // 마커 이미지를 생성합니다
                var markerImage = new kakao.maps.MarkerImage(imageSrc, imageSize);

                var marker = new kakao.maps.Marker({
                    map: map, // 마커를 표시할 지도
                    title : '지도', // 마커의 타이틀, 마커에 마우스를 올리면 타이틀이 표시됩니다
                    position: coords, // 마커를 표시할 위치
                    image : markerImage // 마커 이미지
                });



                var iwContent = '<div style="padding:5px;">랭킹:{{s.rk}} / {{s.itsBroNm}} </div>', // 인포윈도우에 표출될 내용으로 HTML 문자열이나 document element가 가능합니다
                iwRemoveable = true; // removeable 속성을 ture 로 설정하면 인포윈도우를 닫을 수 있는 x버튼이 표시됩니다

                // 인포윈도우를 생성합니다
                var infowindow = new kakao.maps.InfoWindow({
                    content : iwContent,
                });


                // 마커에 mouseover 이벤트와 mouseout 이벤트를 등록합니다
                // 이벤트 리스너로는 클로저를 만들어 등록합니다
                // for문에서 클로저를 만들어 주지 않으면 마지막 마커에만 이벤트가 등록됩니다
                kakao.maps.event.addListener(marker, 'mouseover', makeOverListener(map, marker, infowindow));
                kakao.maps.event.addListener(marker, 'mouseout', makeOutListener(infowindow));

                // 인포윈도우를 표시하는 클로저를 만드는 함수입니다
                function makeOverListener(map, marker, infowindow) {
                    return function() {
                        infowindow.open(map, marker);
                    };
                }

                // 인포윈도우를 닫는 클로저를 만드는 함수입니다
                function makeOutListener(infowindow) {
                    return function() {
                        infowindow.close();
                    };
                }

            }
        })
    };
    {% endfor %}

    console.log(addressList);


    </script>





    <table style="display:inline; float:right;" border="1">
        <tr><th>랭킹</th><th>사진</th><th>상호</th><th>지역 코드</th><th>지역이름</th><th>기준연월</th><th>상세주소</th></tr>
    {% for s in toList %}
        <tr>
            <td>{{s.rk}}</td>
            <td><img style="width:100px; height:100px;" class="img-concert" src="{{s.imgLink}}" /></td>
            <td>{{s.itsBroNm}}</td>
            <td>{{s.areaCode}}</td>
            <td>{{s.areaNm}}</td>
            <td>{{s.baseYm}}</td>
            <td>{{s.dtlAddrNm}}</td>
        </tr>

    {% endfor %}
    </table>

</div>

<div style="display:block;">
<!-- 페이지네이션을 위한 코드 시작 -->
{% if block_start - 1 > 0 %}
    <a href="{{url_for('nationWide.nationWide_info', page=block_start - 1)}}">[이전]</a>
{% endif %}

{% for i in range(block_start, block_end + 1)%}
    <!-- 데이터가 존재하지 않는 페이지는 화면에 나타내지 않기 위한 조건문 -->
    {% if i > last_page_num %}

    {% else %}
        {% if i == page %}
            <b>{{ i }}</b>
        {% else %}
            <a href="{{url_for('nationWide.nationWide_info', page=i)}}">{{ i }}</a>
        {% endif %}
    {% endif %}
{% endfor %}

{% if block_end < last_page_num %}
    <a href="{{url_for('nationWide.nationWide_info', page=block_end + 1)}}">[다음]</a>
{% endif %}
<!-- 페이지네이션을 위한 코드 끝 -->
</div>

</body>
</html>

공공데이터활용/dataMiniProject/templates/nationWide/stList.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h3>{{routeid}} 노선의 경유 정류소</h3>
<table border="1">
    <tr><th>순번</th><th>정류소 고유번호</th><th>정류소명</th><th>첫차시간</th><th>막차시간</th><th>위치 X</th><th>위치 Y</th></tr>
{% for s in stList %}
    <tr>
        <td>{{s.seq}}</td>
        <td>{{s.arsId}}</td>
        <td>{{s.stationNm}}</td>
        <td>{{s.beginTm}}</td>
        <td>{{s.lastTm}}</td>
        <td>{{s.gpsX}}</td>
        <td>{{s.gpsY}}</td>
    </tr>
{% endfor %}
</table>
</body>
</html>